### ISSUE TITLE
Sid plz upload the session ppt 

### ISSUE THREAD

**Issue by XP2016India** [XP2016India/Pitfalls-of-Continuous-Deployment#1]
Sid plz upload the session ppt

**Comment by siddhi** [comment]
This workshop was fully hands on and did not have any presentation slides. For the final output of the workshop, you can get it here - https://github.com/XP2016India/Pitfalls-of-Continuous-Deployment/blob/master/Jenkinsfile

**Comment by XP2016India** [comment]
ok thanks SID :)

regards
RT
